services:
  mysql:
    image: mysql:8.0
    container_name: mysql_proyecto_final
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto_final
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    container_name: proyecto_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: proyecto_final
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
